/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AsistenteRouteImport } from './routes/asistente'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuditPdfRouteImport } from './routes/api/audit-pdf'

const AsistenteRoute = AsistenteRouteImport.update({
  id: '/asistente',
  path: '/asistente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditPdfRoute = ApiAuditPdfRouteImport.update({
  id: '/api/audit-pdf',
  path: '/api/audit-pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/api/audit-pdf': typeof ApiAuditPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/api/audit-pdf': typeof ApiAuditPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/api/audit-pdf': typeof ApiAuditPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/asistente' | '/api/audit-pdf'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/asistente' | '/api/audit-pdf'
  id: '__root__' | '/' | '/asistente' | '/api/audit-pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsistenteRoute: typeof AsistenteRoute
  ApiAuditPdfRoute: typeof ApiAuditPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/asistente': {
      id: '/asistente'
      path: '/asistente'
      fullPath: '/asistente'
      preLoaderRoute: typeof AsistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit-pdf': {
      id: '/api/audit-pdf'
      path: '/api/audit-pdf'
      fullPath: '/api/audit-pdf'
      preLoaderRoute: typeof ApiAuditPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsistenteRoute: AsistenteRoute,
  ApiAuditPdfRoute: ApiAuditPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
