/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuditPdfRouteImport } from './routes/api/audit-pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditPdfRoute = ApiAuditPdfRouteImport.update({
  id: '/api/audit-pdf',
  path: '/api/audit-pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/audit-pdf': typeof ApiAuditPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/audit-pdf': typeof ApiAuditPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/audit-pdf': typeof ApiAuditPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/audit-pdf'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/audit-pdf'
  id: '__root__' | '/' | '/api/audit-pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAuditPdfRoute: typeof ApiAuditPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit-pdf': {
      id: '/api/audit-pdf'
      path: '/api/audit-pdf'
      fullPath: '/api/audit-pdf'
      preLoaderRoute: typeof ApiAuditPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAuditPdfRoute: ApiAuditPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
