/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EconomiaRouteImport } from './routes/economia'
import { Route as AuditorRouteImport } from './routes/auditor'
import { Route as AsistenteRouteImport } from './routes/asistente'
import { Route as IndexRouteImport } from './routes/index'

const EconomiaRoute = EconomiaRouteImport.update({
  id: '/economia',
  path: '/economia',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditorRoute = AuditorRouteImport.update({
  id: '/auditor',
  path: '/auditor',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenteRoute = AsistenteRouteImport.update({
  id: '/asistente',
  path: '/asistente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/auditor': typeof AuditorRoute
  '/economia': typeof EconomiaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/auditor': typeof AuditorRoute
  '/economia': typeof EconomiaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/auditor': typeof AuditorRoute
  '/economia': typeof EconomiaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/asistente' | '/auditor' | '/economia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/asistente' | '/auditor' | '/economia'
  id: '__root__' | '/' | '/asistente' | '/auditor' | '/economia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsistenteRoute: typeof AsistenteRoute
  AuditorRoute: typeof AuditorRoute
  EconomiaRoute: typeof EconomiaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/economia': {
      id: '/economia'
      path: '/economia'
      fullPath: '/economia'
      preLoaderRoute: typeof EconomiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditor': {
      id: '/auditor'
      path: '/auditor'
      fullPath: '/auditor'
      preLoaderRoute: typeof AuditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistente': {
      id: '/asistente'
      path: '/asistente'
      fullPath: '/asistente'
      preLoaderRoute: typeof AsistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsistenteRoute: AsistenteRoute,
  AuditorRoute: AuditorRoute,
  EconomiaRoute: EconomiaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
